# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

spring:
    application:
        name: archinotesx
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
#    cors:
#       allowed-methods: GET, PUT, POST, DELETE, OPTIONS
#       allowed-headers: "*"
#       exposed-headers: X-Total-Count, Link
#       allow-credentials: true
#       max-age: 1800
    mail:
        from: archinotesx@localhost
    security:
        authentication:
            jwt:
                secret: 3b666e9dfcb4b79c5afab5ab57fc4f29da68db4a
                # Token is valid 24 hours
                tokenValidityInSeconds: 3600
    swagger:
        title: ArchinotesX API
        description: ArchinotesX API documentation
        version: 1.0.0
        termsOfServiceUrl: http://www-03.ibm.com/software/sla/sladb.nsf/sla/bm?Open
        contactName: Lorena Salamanca
        contactUrl:
        contactEmail:
        license: Apache License Version 2.0
        licenseUrl: https://github.com/IBM-Bluemix/news-aggregator/blob/master/LICENSE
