# ===================================================================
# Spring Boot configuration.
#
# This configuration will be overriden by the Spring profile you use,
# for example application-dev.yml if you use the "dev" profile.
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================


spring:
    application:
        name: sicc
    jpa:
        open-in-view: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.springframework.boot.orm.jpa.hibernate.SpringNamingStrategy
    messages:
        basename: i18n/messages
    mvc:
        favicon:
            enabled: false
    thymeleaf:
        mode: XHTML

security:
    basic:
        enabled: false

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000
    cors:
       allowed-methods: GET, PUT, POST, DELETE, OPTIONS
       allowed-headers: "*"
       exposed-headers: X-Total-Count, Link
       allow-credentials: true
       max-age: 1800
    mail:
        from: sicc@localhost
    security:
        authentication:
            jwt:
                secret: 3b666e9dfcb4b79c5afab5ab57fc4f29da68db4a
                # Token is valid 24 hours
                tokenValidityInSeconds: 3600
    swagger:
        title: sicc API
        description: sicc API documentation
        version: 0.0.1
        termsOfServiceUrl:
        contactName:
        contactUrl:
        contactEmail:
        license:
        licenseUrl:

# ===================================================================
# Propiedades de SICC
# ===================================================================

sicc:
    criteriosAceptacion:
        o1:
        # Criterio de O1 representa índice de mortalidad máximo (Menor a 0.13) y kilometros respectivamente
            maximoIndiceMortalidad: 0.12
            longitudConcesion: 198.35
            ponderadoContrato: 0.01
            nombreIndicador: Índice de mortalidad.
        # Bucket Amazon S3
            nombreBucket: O1
        o2:
        # Criterio de O2 representada en metros
           maximoLongitudRetencion: 300 
           ponderadoContrato: 0.0895
           nombreIndicador: Ocupación de carriles.
        # Bucket Amazon S3
           nombreBucket: O2
        o3:
        # Criterio de O3 representa tiempo en minutos y unidades de peajes activos
            tamañoIntervalo: 10
            cantidadMaximaVehiculos: 10
            denominadorDeCantidadPeajes: 2
            tiempoMaximoCola: 60
            ponderadoContrato: 0.1050
            nombreIndicador: Cola de peaje.
        # Bucket Amazon S3
            nombreBucket: O3
        o4:
        # Criterios de O4 representan tiempo en minutos
            maximoEventosIncumplimiento: 3
            tiempoSenalizacion: 60
            tiempoDespeje:
                calzadaMenos200: 240
                calzadaEntre200y2000: 1440
                bermaMenos200: 1440
                bermaEntre200y2000: 1440
                nuevosDispositivosMayor2000: 10080
                mayorDificultadMayor2000: 43200
            ponderadoContrato: 0.1050
            nombreIndicador: Tiempo de atención de incidentes.
        # Bucket Amazon S3
            nombreBucket: O4
        o5:
        # Criterios de O5 representan tiempo en minutos
            maximoEventosIncumplimiento: 3
            tiempoSenalizacion:
                senalizacion: 30
                ambulancia: 30
                grua: 60
            ponderadoContrato: 0.0550
            nombreIndicador: Tiempo de atención de accidentes y emergencias.
        # Bucket Amazon S3
            nombreBucket: O5
        o6:
        # Criterios de O6 (Disponibilidad del sistema) representa porcentaje
            ponderadoContrato: 0.0525
            nombreIndicador: Disponibilidad del SICC.
            # Bucket Amazon S3
            nombreBucket: O6
        e6:
        # Criterios de E6 representan milímetros y metros cuadrados respectivamente
            maximoKilometrosIncumplimiento: 0
            maximoProfundidad: 0.25
            maximoSuperficie: 0.05
            ponderadoContrato: 0.04025
            nombreIndicador: Baches.
        # Criterio de E6 representan días
            tiempoAtencion: 1
        # Bucket Amazon S3
            nombreBucket: E6
        e8:
        # Criterios de E8 representan metros
            maximoKilometrosIncumplimiento: 1
            alturaVegetacion: 0.3
            maximaCantidadArticulosBasura: 25
            ponderadoContrato: 0.1510
            nombreIndicador: Estado de márgenes, separador central. Área de servicio y corredor del proyecto
        # Criterio de E8 representan días
            tiempoAtencion: 7
        # Bucket Amazon S3
            nombreBucket: E8
        e10:
        # Criterios de E10 representa porcentaje de obstrucción
            maximoKilometrosIncumplimiento: 1
            seccionObstruida: 25
            ponderadoContrato: 0.12
            nombreIndicador: Drenajes superficiales, longitudinal y trasversal.
        # Criterio de E10 representan días
            tiempoAtencion: 7
        # Bucket Amazon S3
            nombreBucket: E10
        e11:
        # Criterios de E11 representa porcentaje de retroflectividad
            maximoKilometrosIncumplimiento: 2
            retroflectividad: 80
            porcentajeDeInstalacion: 0.8
            ponderadoContrato: 0.0805
            
            angulosMedicionNivelesCombo:
                
                anguloPunto1EntradaMenos4:  0.1 | -4           
                anguloPunto1EntradaMas30:  0.1 | +30      
                anguloPunto2EntradaMenos4:  0.2 | -4
                anguloPunto2EntradaMas30:  0.2 | +30
                anguloPunto5EntradaMenos4:  0.5 | -4
                anguloPunto5EntradaMas30:  0.5 | +30
            
            nivelesMinimosRetroreflexionMicroprismas:
                
                anguloPunto1EntradaMenos4Blanco: 500
                anguloPunto1EntradaMenos4Amarillo: 380
                anguloPunto1EntradaMenos4Naranja: 200
                anguloPunto1EntradaMenos4Verde: 70 
                anguloPunto1EntradaMenos4Rojo: 90
                anguloPunto1EntradaMenos4Azul: 42
                anguloPunto1EntradaMenos4Marron: 25
                anguloPunto1EntradaMenos4AmarilloVerdeFluorescente: 400
                anguloPunto1EntradaMenos4AmarilloFluorescente: 300
                anguloPunto1EntradaMenos4NaranjaFluorescente: 150
                
                anguloPunto1EntradaMas30Blanco: 240
                anguloPunto1EntradaMas30Amarillo: 175
                anguloPunto1EntradaMas30Naranja: 94
                anguloPunto1EntradaMas30Verde: 32
                anguloPunto1EntradaMas30Rojo: 42
                anguloPunto1EntradaMas30Azul: 20
                anguloPunto1EntradaMas30Marron: 12
                anguloPunto1EntradaMas30AmarilloVerdeFluorescente: 185
                anguloPunto1EntradaMas30AmarilloFluorescente: 140
                anguloPunto1EntradaMas30NaranjaFluorescente: 70
    
                anguloPunto2EntradaMenos4Blanco: 360
                anguloPunto2EntradaMenos4Amarillo: 270
                anguloPunto2EntradaMenos4Naranja: 145
                anguloPunto2EntradaMenos4Verde: 50
                anguloPunto2EntradaMenos4Rojo: 65
                anguloPunto2EntradaMenos4Azul: 30
                anguloPunto2EntradaMenos4Marron: 18
                anguloPunto2EntradaMenos4AmarilloVerdeFluorescente: 290
                anguloPunto2EntradaMenos4AmarilloFluorescente: 220
                anguloPunto2EntradaMenos4NaranjaFluorescente: 105
                
                anguloPunto2EntradaMas30Blanco: 170
                anguloPunto2EntradaMas30Amarillo: 135
                anguloPunto2EntradaMas30Naranja: 68
                anguloPunto2EntradaMas30Verde: 25
                anguloPunto2EntradaMas30Rojo: 30
                anguloPunto2EntradaMas30Azul: 14
                anguloPunto2EntradaMas30Marron: 8.5
                anguloPunto2EntradaMas30AmarilloVerdeFluorescente: 135
                anguloPunto2EntradaMas30AmarilloFluorescente: 100
                anguloPunto2EntradaMas30NaranjaFluorescente: 50
                
                
                anguloPunto5EntradaMenos4Blanco: 150
                anguloPunto5EntradaMenos4Amarillo: 110
                anguloPunto5EntradaMenos4Naranja: 60
                anguloPunto5EntradaMenos4Verde: 21
                anguloPunto5EntradaMenos4Rojo: 27
                anguloPunto5EntradaMenos4Azul: 13
                anguloPunto5EntradaMenos4Marron: 7.5
                anguloPunto5EntradaMenos4AmarilloVerdeFluorescente: 120
                anguloPunto5EntradaMenos4AmarilloFluorescente: 90
                anguloPunto5EntradaMenos4NaranjaFluorescente: 45
                
                anguloPunto5EntradaMas30Blanco: 72
                anguloPunto5EntradaMas30Amarillo: 54
                anguloPunto5EntradaMas30Naranja: 28
                anguloPunto5EntradaMas30Verde: 10
                anguloPunto5EntradaMas30Rojo: 13
                anguloPunto5EntradaMas30Azul: 6
                anguloPunto5EntradaMas30Marron: 3.5
                anguloPunto5EntradaMas30AmarilloVerdeFluorescente: 55
                anguloPunto5EntradaMas30AmarilloFluorescente: 40
                anguloPunto5EntradaMas30NaranjaFluorescente: 22
                
                
            nombreIndicador: Señalización vertical.
        # Criterio de E8 representan días
            tiempoAtencionPorReflectividad: 7
            tiempoAtencionPorIlegibilidad: 2
        # Bucket Amazon S3
            nombreBucket: E11
        e12:
        # Criterios de E12 representa medidas de luces
            maximoKilometrosIncumplimiento: 1
            blancasCandelasMaximo: 160
            blancasMetrosMaximo: 140
            amarillasCandelasMaximo: 140
            amarillasMetrosMaximo: 120
            nota1: 15
            nota2: 30
            ponderadoContrato: 0.0805
            nombreIndicador: Señalización horizontal.
        # Criterio de E12 representan días
            tiempoAtencion: 7
        # Bucket Amazon S3
            nombreBucket: E12
        e13:
        # Criterios de E13 representa longitud en metros
            maximoKilometrosIncumplimiento: 2
            maximaLongitudTramo: 20
            ponderadoContrato: 0.0805
            nombreIndicador: Barreras y elementos de contención.
        #Criterio de E12 representan meses
            tiempoAtencion: 1
        # Bucket Amazon S3
            nombreBucket: E13
        e24:
        # Criterios de E24 representa medidas de luces
            maximoKilometrosIncumplimiento: 99999999
            maximoDesportillamientosKilometro: 30
            ponderadoContrato: 0.04025
            nombreIndicador: Desportillamiento.
         # Criterio de E24 representan días
            tiempoAtencion: 14
         # Bucket Amazon S3
            nombreBucket: E24
    unidadFuncionalDefault: UF0
    ubicacionBucketGlobal: http://s3.amazonaws.com/
    endpointCloudWatch: http://monitoring.us-east-1.amazonaws.com/
    prefijoNombreArchivo: _
    autoScalingGroupName: ASG_NAME
    awsAccessKey: AWS_ACCESS_KEY_ID
    awsSecretKey: AWS_SECRET_ACCESS_KEY
